[package]
name = "axum-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
apitally = { path = "../../" }
axum = "0.7.9"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
tokio = { version = "1.42.0", features = ["full"] }
